apiVersion: apps/v1
kind: Deployment
metadata:
  name: sparksbm-keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sparksbm-keycloak
  template:
    metadata:
      labels:
        app: sparksbm-keycloak
    spec:
      containers:
      - name: keycloak
        image: quay.io/keycloak/keycloak:latest
        args: ["start-dev"]
        env:
        - name: KC_DB
          value: "postgres"
        - name: KC_DB_URL
          value: "jdbc:postgresql://ep-young-bread-a1f8nuq1-pooler.ap-southeast-1.aws.neon.tech/SparksBM?sslmode=require"
        - name: KC_DB_USERNAME
          value: "neondb_owner"
        - name: KC_DB_PASSWORD
          value: "npg_UYhru41qVIZS"
        - name: KC_TRANSACTION_XA_ENABLED
          value: "false"
        - name: KEYCLOAK_ADMIN
          value: "admin"
        - name: KEYCLOAK_ADMIN_PASSWORD
          value: "admin123"
        - name: KC_PROXY
          value: "edge"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak
spec:
  selector:
    app: sparksbm-keycloak
  ports:
    - port: 8080
      targetPort: 8080
