apiVersion: apps/v1
kind: Deployment
metadata:
  name: sparksbm-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sparksbm-app
  template:
    metadata:
      labels:
        app: sparksbm-app
    spec:
      containers:
      - name: sparksbm-app
        image: gcr.io/PROJECT_ID_PLACEHOLDER/sparksbm-app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:postgresql://ep-young-bread-a1f8nuq1-pooler.ap-southeast-1.aws.neon.tech/SparksBM?sslmode=require"
        - name: SPRING_DATASOURCE_USERNAME
          value: "neondb_owner"
        - name: SPRING_DATASOURCE_PASSWORD
          value: "npg_UYhru41qVIZS"
        - name: SPRING_RABBITMQ_HOST
          value: "rabbitmq"
        - name: KEYCLOAK_AUTH_SERVER_URL
          value: "http://keycloak:8080"
---
apiVersion: v1
kind: Service
metadata:
  name: sparksbm-app
spec:
  selector:
    app: sparksbm-app
  ports:
    - port: 8080
      targetPort: 8080
